### ISSUE TITLE
尝试启动项目后，访问正文页面，报错无法显示。

### ISSUE THREAD

**Issue by ZhaoTim** [hehehai/h-blog#6]
你好，很喜欢博客的风格~所以把项目下载到了本地，尝试运行起来。

可是，当我访问文章的页面时，页面上报了这个错误：

```
Unhandled Runtime Error
TypeError: _jsx is not a function

Call Stack
_createMdxContent
eval at <anonymous> (webpack-internal:///./node_modules/.pnpm/next-mdx-remote@4.4.1_biqbaboplfbrettd7655fr4n2y/node_modules/next-mdx-remote/dist/index.js), <anonymous> (24:16)
```

我尝试搜索这个错误类型，发现好像是 [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote/issues/350 )这个库导致的错误，不知道你在本地是否遇到了这个问题~

**Comment by hehehai** [comment]
哇，谢谢🥰。我会尽快补充一个文档，编写该博客的安装部署使用教程。

我本地使用 pnpm 安装的依赖，没有发现这个问题。

我查询到了这个解决方式：
https://github.com/hashicorp/next-mdx-remote/issues/350#issuecomment-1461558918

1. 我的 Node v20.8.1
2. 检查 package.json 里的依赖版本是否有变化 （我本地是："next-mdx-remote": "^4.1.0"）
3. 尝试删除 node_modules 和 pnpm-lock 文件，重试
